// <auto-generated />
using System;
using DecisionHelper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DecisionHelper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223121125_AddDecisionOptionsTable")]
    partial class AddDecisionOptionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DecisionHelper.Models.DecisionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlairId")
                        .HasColumnType("int");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlairId");

                    b.ToTable("DecisionOptions");
                });

            modelBuilder.Entity("DecisionHelper.Models.DecisionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlairId")
                        .HasColumnType("int");

                    b.Property<string>("WinningOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlairId");

                    b.ToTable("DecisionRecords");
                });

            modelBuilder.Entity("DecisionHelper.Models.Flair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flairs");
                });

            modelBuilder.Entity("DecisionHelper.Models.DecisionOption", b =>
                {
                    b.HasOne("DecisionHelper.Models.Flair", "Flair")
                        .WithMany()
                        .HasForeignKey("FlairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flair");
                });

            modelBuilder.Entity("DecisionHelper.Models.DecisionRecord", b =>
                {
                    b.HasOne("DecisionHelper.Models.Flair", "Flair")
                        .WithMany("DecisionRecords")
                        .HasForeignKey("FlairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flair");
                });

            modelBuilder.Entity("DecisionHelper.Models.Flair", b =>
                {
                    b.Navigation("DecisionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
